burger/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [path("", views.main_page, name="main")]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("burger.urls", namespace="main")),
    path("admin/", admin.site.urls),
    path("menu/", include("menu.urls", namespace="menu")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

menu/urls.py
from django.urls import path
from . import views

app_name = "menu"

urlpatterns = [path("", views.menu, name="main")]

menu/models.py
from django.db import models

# Create your models here.

from django.db import models

# Create your models here.


class Ingredient(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    fats = models.PositiveSmallIntegerField(default=0, blank=True)
    saturated_fats = models.PositiveSmallIntegerField(default=0, blank=True)
    carbohydrates = models.PositiveSmallIntegerField(default=0, blank=True)
    sugar = models.PositiveSmallIntegerField(default=0, blank=True)
    cellulose = models.PositiveSmallIntegerField(default=0, blank=True)
    squirrels = models.PositiveSmallIntegerField(default=0, blank=True)
    salt = models.PositiveSmallIntegerField(default=0, blank=True)
    energy_value = models.PositiveSmallIntegerField(default=0, blank=True)
    allergen = models.JSONField(null=True, blank=True)

    class Meta:
        db_table = "ingredient"
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"

    def __str__(self):
        return self.name


# TODO всё вроде норм посмотреть сохранение в JSON сделать сигнал на изменение m2m и также добавить проверку в метод save burger что при создании объекта всё сразу же просчитывалось; Так же подумать над тем что если из бургера удалили что-то то пропорция должна автоматически удоляться


class AvailableManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(is_available=True)


class Burger(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to="burger_image/")
    price = models.DecimalField(max_digits=5, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0, blank=True)
    is_available = models.BooleanField()
    is_main = models.BooleanField()
    is_president = models.BooleanField()
    is_new = models.BooleanField()
    ingredients = models.ManyToManyField(
        "menu.Ingredient", through="menu.Proportion", related_name="burgers"
    )
    compound = models.JSONField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique=True)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        db_table = "burger"
        ordering = ["is_new", "id"]
        indexes = [
            models.Index(fields=["is_available"]),
            models.Index(fields=["id", "slug"]),
        ]
        verbose_name = "Burger"
        verbose_name_plural = "Burgers"

    def __str__(self):
        return self.name


class Proportion(models.Model):
    burger = models.ForeignKey(Burger, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    weight = models.PositiveSmallIntegerField()

    class Meta:
        db_table = "proportion"
        verbose_name = "Proportion"
        verbose_name_plural = "Proportions"

burger/views.py
from django.shortcuts import render

# Create your views here.


def main_page(request):

    context = {"section": "main"}
    return render(request, "burger/index.html", context=context)

menu/views.py
from django.shortcuts import render

# Create your views here.


def menu(request):
    context = {"section": "menu"}

    return render(request, "menu/menu.html", context=context)

burger/templates/burger/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Burger{% endblock title %}

{% block content %}
<!-- slider_area_start -->
<div class="slider_area">
    <div class="slider_active owl-carousel">
        <div class="single_slider  d-flex align-items-center slider_bg_1 overlay">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-9 col-md-9 col-md-12">
                        <div class="slider_text text-center">
                            <div class="deal_text">
                                <span>Big Deal</span>
                            </div>
                            <h3>Burger <br>
                                Bachelor</h3>
                            <h4>Maxican</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="single_slider  d-flex align-items-center slider_bg_2 overlay">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-9 col-md-9 col-md-12">
                        <div class="slider_text text-center">
                            <div class="deal_text">
                                <span>Big Deal</span>
                            </div>
                            <h3>Burger <br>
                                Bachelor</h3>
                            <h4>Maxican</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider_area_end -->

<div class="best_burgers_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title text-center mb-80">
                    <span>Burger Menu</span>
                    <h3>Best Ever Burgers</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-md-6 col-lg-6">
                <div class="single_delicious d-flex align-items-center">
                    <div class="thumb">
                        {% comment %} <img src="" alt=""> {% endcomment %}
                    </div>
                    <div class="info">
                        <h3>Beefy Burgers</h3>
                        <p>Great way to make your business appear trust and relevant.</p>
                        <span>$5</span>
                    </div>
                </div>
            </div> 
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="iteam_links">
                    <a class="boxed-btn5" href="Menu.html">More Items</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- features_room_start -->
{% include "president_area.html" %}
<!-- features_room_end -->
<!-- about_area_start -->
<div class="about_area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-xl-6 col-lg-6 col-md-6">
                <div class="about_thumb2">
                    <div class="img_1">
                        <img src="{% static 'img/about/1.png' %}" alt="">
                    </div>
                    <div class="img_2">
                        <img src="{% static 'img/about/2.png' %}" alt="">
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-lg-5 offset-lg-1 col-md-6">
                <div class="about_info">
                    <div class="section_title mb-20px">
                        <span>About Us</span>
                        <h3>Best Burger <br>
                            in your City</h3>
                    </div>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have
                        suffered alteration in some form, by injected humour, or randomised words which don't look
                        even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be
                        sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum
                        generators on the Internet tend to repeat predefined chunks as necessary, making this the
                        first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined
                        with a handful of model sentence structures, to generate</p>
                    <div class="img_thumb">
                        <img src="{% static 'img/jessica-signature.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- about_area_end -->
<!-- video_area_start -->
<div class="video_area video_bg overlay">
    <div class="video_area_inner text-center">
        <h3>Burger <br>
            Bachelor</h3>
        <span>How we make delicious Burger</span>
        <div class="video_payer">
            <a href="https://youtu.be/dQw4w9WgXcQ?si=SUAqZrV0Z89MJk9X" class="video_btn popup-video">
                <i class="fa fa-play"></i>
            </a>
        </div>
    </div>
</div>
<!-- video_area_end -->

<!-- testimonial_area_start  -->
{% include "happy_customers.html" %}
<!-- testimonial_area_ned  -->
{% endblock content %}

menu/templates/menu/menu.html
{% extends "base.html" %}

{% block title %}
    Burger - menu
{% endblock title %}

{% block content %}

<!-- bradcam_area_start -->
<div class="bradcam_area breadcam_bg overlay">
    <h3>Menu</h3>
</div>
<!-- bradcam_area_end -->

<!-- best_burgers_area_start  -->
<div class="best_burgers_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title text-center mb-80">
                    <span>Burger Menu</span>
                    <h3>Best Ever Burgers</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-md-6 col-lg-6">
                <div class="single_delicious d-flex align-items-center">
                    <div class="thumb">
                        <img src="img/burger/1.png" alt="">
                    </div>
                    <div class="info">
                        <h3>Beefy Burgers</h3>
                        <p>Great way to make your business appear trust and relevant.</p>
                        <span>$5</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- best_burgers_area_end  -->

{% include "president_area.html" %}

{% include "happy_customers.html" %}

{% endblock content %}

templates/base.html
{% load compress %}
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    {% compress css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"  >
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" >
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" >
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" >
        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" >
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" >
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" >
        <link rel="stylesheet" href="{% static 'css/animate.css' %}" >
        <link rel="stylesheet" href="{% static 'css/slicknav.css' %}" >
        <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    {% endcompress %}
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid p-0">
                    <div class="row align-items-center no-gutters">
                        <div class="col-xl-5 col-lg-5">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="{% if section == 'main' %}active{% endif %}" href="{% url "main:main" %}">Home</a></li>
                                        <li><a class="{% if section == 'menu' %}active{% endif %}" href="{% url "menu:main" %}">Menu</a></li>
                                        <li><a class="{% if section == 'about' %}active{% endif %}" href="about.html">About</a></li>
                                        <li><a class="{% if section == 'blog' %}active{% endif %}" href="#">Blog</a></li>
                                        <li><a class="{% if section == 'contact' %}active{% endif %}" href="contact.html">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo-img">
                                <a href="index.html">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-5 d-none d-lg-block">
                            <div class="book_room">
                                <div class="socail_links">
                                    <ul>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-instagram"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-twitter"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-facebook"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-google-plus"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="book_btn d-none d-xl-block">
                                    <a class="#" href="#">+10 367 453 7382</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block content %}{% endblock content %}

    <!-- footer-start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget text-center ">
                            <h3 class="footer_title pos_margin">
                                New York
                            </h3>
                            <p>5th flora, 700/D kings road, <br>
                                green lane New York-1782 <br>
                                <a href="#">info@burger.com</a>
                            </p>
                            <a class="number" href="#">+10 378 483 6782</a>

                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget text-center ">
                            <h3 class="footer_title pos_margin">
                                California
                            </h3>
                            <p>5th flora, 700/D kings road, <br>
                                green lane New York-1782 <br>
                                <a href="#">info@burger.com</a>
                            </p>
                            <a class="number" href="#">+10 378 483 6782</a>

                        </div>
                    </div>
                    <div class="col-xl-4 col-md-12 col-lg-4">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Stay Connected
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Sign Up</button>
                            </form>
                            <p class="newsletter_text">Stay connect with us to get exclusive offer!</p>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4">
                        <div class="socail_links text-center">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="ti-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->

{% compress js %}
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/ajax-form.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/scrollIt.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endcompress %}

</body>

</html>

templates/happy_customers.html
<div class="testimonial_area ">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="section_title mb-60 text-center">
                    <span>Testimonials</span>
                    <h3>Happy Customers</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12">
                <div class="testmonial_active owl-carousel">
                    <!-- start feedback -->
                    <div class="single_carousel">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="single_testmonial text-center">
                                    <p>“Donec imperdiet congue orci consequat mattis. Donec rutrum porttitor
                                        sollicitudin. Pellentesque id dolor tempor sapien feugiat ultrices nec
                                        sed
                                        neque.</p>
                                    <div class="testmonial_author">
                                        <h4>Kristiana Chouhan</h4>
                                        <div class="stars">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star-half"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end feedback -->
                </div>
            </div>
        </div>
    </div>
</div>

templates/president_area.html
<!-- features_room_start -->
<div class="Burger_President_area">
        <div class="Burger_President_here">
            <div class="single_Burger_President">
                <div class="room_thumb">
                    {% comment %} <img src="img/burgers/1.png" alt=""> {% endcomment %}
                    <div class="room_heading d-flex justify-content-between align-items-center">
                        <div class="room_heading_inner">
                            <span>$20</span>
                            <h3>The Burger President</h3>
                            <p>Great way to make your business appear trust <br> and relevant.</p>
                            <a href="#" class="boxed-btn3">Order Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single_Burger_President">
                <div class="room_thumb">
                    {% comment %} <img src="{% static 'img/burgers/2.png' %}" alt=""> {% endcomment %}
                    <div class="room_heading d-flex justify-content-between align-items-center">
                        <div class="room_heading_inner">
                            <span>$20</span>
                            <h3>The Burger President</h3>
                            <p>Great way to make your business appear trust <br> and relevant.</p>
                            <a href="#" class="boxed-btn3">Order Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
<!-- features_room_end -->